# Generated by Django 6.0.8 on 2026-08-05 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('framework', models.CharField(choices=[('static', 'Static Website'), ('react', 'React App'), ('node', 'Node.js Server'), ('django', 'Django App'), ('flask', 'Flask App')], default='static', max_length=20)),
                ('status', models.CharField(choices=[('stopped', 'Stopped'), ('building', 'Building'), ('running', 'Running'), ('failed', 'Failed')], default='stopped', max_length=20)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('container_id', models.CharField(blank=True, default='', max_length=100)),
                ('custom_domain', models.CharField(blank=True, default='', max_length=255)),
                ('git_repo', models.CharField(blank=True, default='', max_length=255)),
                ('env_vars', models.JSONField(blank=True, default=dict)),
                ('cpu_limit', models.CharField(default='0.5', max_length=20)),
                ('ram_limit', models.CharField(default='512M', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
