# Generated by Django 6.0.8 on 2026-08-05 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('db_name', models.CharField(max_length=100, unique=True)),
                ('db_user', models.CharField(max_length=100)),
                ('db_password', models.CharField(max_length=255)),
                ('host', models.CharField(default='127.0.0.1', max_length=255)),
                ('port', models.IntegerField(default=3306)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_databases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
